CREATE TABLE "mytable" (
  "-- Database: rpms" text
);

INSERT INTO "mytable" ("-- Database: rpms")
VALUES
('-- Table structure for table `administrators`'),
('DROP TABLE IF EXISTS `administrators`;'),
('CREATE TABLE `administrators` ('),
('`user_id` varchar(36) NOT NULL'),
('`username` varchar(50) NOT NULL'),
('`password` varchar(255) NOT NULL'),
('`name` varchar(100) NOT NULL'),
('`age` int NOT NULL'),
('`gender` varchar(10) NOT NULL'),
('`phone` varchar(15) NOT NULL'),
('`email` varchar(100) NOT NULL'),
('`role` varchar(50) NOT NULL'),
('`official_email` varchar(100) NOT NULL'),
('`supervisor_name` varchar(100) NOT NULL'),
('PRIMARY KEY (`user_id`)'),
('UNIQUE KEY `username` (`username`)'),
(');'),
('INSERT INTO `administrators` VALUES'),
('(''A001'''),
('-- Table structure for table `appointments`'),
('DROP TABLE IF EXISTS `appointments`;'),
('CREATE TABLE `appointments` ('),
('`appointment_id` varchar(36) NOT NULL'),
('`patient_id` varchar(36) NOT NULL'),
('`doctor_id` varchar(36) NOT NULL'),
('`appointment_datetime` datetime NOT NULL'),
('`purpose` text NOT NULL'),
('`status` varchar(20) NOT NULL'),
('PRIMARY KEY (`appointment_id`)'),
('KEY `patient_id` (`patient_id`)'),
('KEY `doctor_id` (`doctor_id`)'),
('CONSTRAINT `appointments_ibfk_1` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`user_id`) ON DELETE CASCADE'),
('CONSTRAINT `appointments_ibfk_2` FOREIGN KEY (`doctor_id`) REFERENCES `doctors` (`user_id`) ON DELETE CASCADE'),
('CONSTRAINT `status_check` CHECK (`status` IN (''REQUESTED'''),
(');'),
('INSERT INTO `appointments` VALUES'),
('(''AP001'''),
('(''AP002'''),
('-- Table structure for table `doctor_feedback`'),
('DROP TABLE IF EXISTS `doctor_feedback`;'),
('CREATE TABLE `doctor_feedback` ('),
('`feedback_id` varchar(36) NOT NULL'),
('`doctor_id` varchar(36) NOT NULL'),
('`patient_id` varchar(36) NOT NULL'),
('`timestamp` datetime NOT NULL'),
('`diagnosis` text NOT NULL'),
('`recommendations` text NOT NULL'),
('`prescription` text NOT NULL'),
('PRIMARY KEY (`feedback_id`)'),
('KEY `doctor_id` (`doctor_id`)'),
('KEY `patient_id` (`patient_id`)'),
('CONSTRAINT `doctor_feedback_ibfk_1` FOREIGN KEY (`doctor_id`) REFERENCES `doctors` (`user_id`) ON DELETE CASCADE'),
('CONSTRAINT `doctor_feedback_ibfk_2` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`user_id`) ON DELETE CASCADE'),
(');'),
('INSERT INTO `doctor_feedback` VALUES'),
('(''FB001'''),
('(''FB002'''),
('(''FB003'''),
('-- Table structure for table `doctor_patient_assignments`'),
('DROP TABLE IF EXISTS `doctor_patient_assignments`;'),
('CREATE TABLE `doctor_patient_assignments` ('),
('`doctor_id` varchar(36) NOT NULL'),
('`patient_id` varchar(36) NOT NULL'),
('PRIMARY KEY (`doctor_id`'),
('KEY `patient_id` (`patient_id`)'),
('CONSTRAINT `doctor_patient_assignments_ibfk_1` FOREIGN KEY (`doctor_id`) REFERENCES `doctors` (`user_id`) ON DELETE CASCADE'),
('CONSTRAINT `doctor_patient_assignments_ibfk_2` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`user_id`) ON DELETE CASCADE'),
(');'),
('INSERT INTO `doctor_patient_assignments` VALUES'),
('(''D002'''),
('-- Table structure for table `doctors`'),
('DROP TABLE IF EXISTS `doctors`;'),
('CREATE TABLE `doctors` ('),
('`user_id` varchar(36) NOT NULL'),
('`username` varchar(50) NOT NULL'),
('`password` varchar(255) NOT NULL'),
('`name` varchar(100) NOT NULL'),
('`age` int NOT NULL'),
('`gender` varchar(10) NOT NULL'),
('`phone` varchar(15) NOT NULL'),
('`email` varchar(100) NOT NULL'),
('`specialization` varchar(100) NOT NULL'),
('`working_hours` varchar(50) NOT NULL'),
('PRIMARY KEY (`user_id`)'),
('UNIQUE KEY `username` (`username`)'),
(');'),
('INSERT INTO `doctors` VALUES'),
('(''D001'''),
('(''D002'''),
('-- Table structure for table `patients`'),
('DROP TABLE IF EXISTS `patients`;'),
('CREATE TABLE `patients` ('),
('`user_id` varchar(36) NOT NULL'),
('`username` varchar(50) NOT NULL'),
('`password` varchar(255) NOT NULL'),
('`name` varchar(100) NOT NULL'),
('`age` int NOT NULL'),
('`gender` varchar(10) NOT NULL'),
('`phone` varchar(15) NOT NULL'),
('`email` varchar(100) NOT NULL'),
('`assigned_doctor` varchar(36) DEFAULT NULL'),
('PRIMARY KEY (`user_id`)'),
('UNIQUE KEY `username` (`username`)'),
('KEY `assigned_doctor` (`assigned_doctor`)'),
('CONSTRAINT `patients_ibfk_1` FOREIGN KEY (`assigned_doctor`) REFERENCES `doctors` (`user_id`) ON DELETE SET NULL'),
(');'),
('INSERT INTO `patients` VALUES'),
('(''P001'''),
('(''P002'''),
('(''P003'''),
('-- Table structure for table `vital_records`'),
('DROP TABLE IF EXISTS `vital_records`;'),
('CREATE TABLE `vital_records` ('),
('`record_id` varchar(36) NOT NULL'),
('`user_id` varchar(50) NOT NULL'),
('`timestamp` datetime NOT NULL'),
('`temperature` double NOT NULL'),
('`heart_rate` int NOT NULL'),
('`systolic_bp` int NOT NULL'),
('`diastolic_bp` int NOT NULL'),
('`respiration_rate` int NOT NULL'),
('`oxygen_saturation` double NOT NULL'),
('`notes` text'),
('`alerts` text'),
('`is_critical` tinyint(1) NOT NULL'),
('PRIMARY KEY (`record_id`)'),
('KEY `user_id` (`user_id`)'),
('CONSTRAINT `vital_records_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `patients` (`user_id`)'),
(');'),
('INSERT INTO `vital_records` VALUES'),
('(''VR001'''),
('(''VR002'''),
('(''VR003'''),
('(''VR004'''),
('(''VR005'''),
('(''VR006'''),
('(''VR007''');
